replicaCount: 3

image:
  repository: my-prod-registry/gameserver
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 3000

ingress:
  enabled: true
  hosts:
    - host: game-server.example.com
      paths:
        - /
