apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry
  namespace: rts
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: registry
  template:
    metadata:
      labels:
        app: registry
    spec:
      containers:
        - name: registry
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.service.port }}
          args:
            - "serve"
            - "/etc/docker/registry/config.yml"
          volumeMounts:
            - name: registry-storage
              mountPath: /var/lib/registry
      volumes:
        - name: registry-storage
          emptyDir: {}
